# Generated by Django 2.0 on 2018-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
    ]
