# Generated by Django 2.0 on 2018-01-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='photogal.Category'),
            preserve_default=False,
        ),
    ]
