# Generated by Django 2.0 on 2018-01-16 11:00

from django.db import migrations, models
import photogal.models


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0006_auto_20180115_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_name',
            field=models.CharField(default='Default Name', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='upload',
            field=models.ImageField(upload_to=photogal.helpers.RandomFileName('uploads')),
        ),
    ]
