# Generated by Django 2.0 on 2018-01-16 11:35

from django.db import migrations, models
import photogal.models


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0007_auto_20180116_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='upload',
            field=models.ImageField(upload_to=photogal.helpers.RandomFileName('uploads')),
        ),
    ]
