# Generated by Django 2.0 on 2018-01-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0008_auto_20180116_1835'),
        ('photogal', '0007_auto_20180116_1851'),
    ]

    operations = [
    ]
