# Generated by Django 2.0 on 2018-01-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0010_picture_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_post_pictures', 'To allow to upload photos'), ('can_show_pictures', 'To allow to show uploaded photos'))},
        ),
    ]
